name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  workflow_dispatch: null
env:
  CARGO_TERM_COLOR: always

jobs:
  auto-merge:
    permissions:
      contents: write
      pull-requests: write

    runs-on: ubuntu-latest

    steps:
    - name: Enable auto-merge for Pull Request
      if: ${{ github.event_name == 'pull_request' && !github.event.pull_request.draft }}
      run: |
        gh pr review --approve "$PR_URL"
        gh pr merge --auto --squash "$PR_URL"
      env:
        PR_URL: ${{github.event.pull_request.html_url}}
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        config:
          - {target: 'x86_64-unknown-linux-gnu'}

    steps:
    - name: Add cross build targets
      run: rustup target add ${{ matrix.config.target }}
    - name: Update Rust toolchain
      run: rustup update
    - name: Install cross
      run: cargo install cross
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      with:
        persist-credentials: false
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
